dist: trusty
sudo: false
language: python
python: '3.6'
before_install:
- export TZ=Asia/Tokyo
install:
- pip install sphinx==1.4.9
- cd ..
- pwd
- ls -la
- git clone https://github.com/python-doc-ja/py27.git py27
- git clone --depth=5 -b intl-2.7 https://github.com/python-doc-ja/cpython-doc-intl.git cpython
- cd cpython/Doc
- ln -s ../../py27-locale locale
- ls -lF locale
- sphinx-build -j4 -D language=ja -D locale_dirs=locale -D gettext_compact=0 -A versionswitcher=1 -E -d build/doctrees . ../../py27
script:
- cd ../../py27
- git config user.email "travis-build-bot@example.com"
- git config user.name "Autobuild bot on Travis-CI"
- git pull origin master
- git add .
- if [ $(git status -s | wc -l) -eq 0 ]; then echo "nothing to commit"; exit 0; fi
- git commit -a -m "update html"
- git push --quiet "https://${GH_TOKEN}@github.com/python-doc-ja/py27.git" master:master
env:
  global:
    secure: b+dE49MUww9FYt5rrzClAfXqOSMpLhsYbmcLcCOI57qiUf8cj3XWw96fdT8rUkKNhkzK16JpoD/XNboEE98amfXvx4ufSm3Q2fe/EmeDEyo/gnarXPjtPkt4pSaNgS7/9Do+A4/Nr940KZCPKvEIvbbSc9182FKrlmgRAjTu4qBmC8UviqoD9jvenMYTsqfLJL27vpyyI2HuU99t80bMfoFgVcTO7KVFYrFABPALa6HhdyOYRv6dd2vVJSbcPC3NC1oUv4uKLSCIwfvTqIRYZMQBfi8tZSF3M2bEAew3sleIM2up8zybilFOnWA71IrZY49pHLPrTHM7jh+/alsWI+cARaDkta+jfJ6q6Dh3PqneXwP2pry1WbpoAGNkPIarK1hMZa6KsSVN9Y7vhdftfT6HiWN+TtZUlnY2WazxBWAfiZWtVMfqOygaObc/awS8z5L7YNTlsm3MND1pT3+iHpmQshg1kuQSLKdHJX2CLJfDL/LQ5Jr51p5MUbB25r/KnN6WENuP7zYtYZHC9v4NTrRNKLGyJZn4efj+o0lwAimXGh9fiY4vhRHhgMg2lMC7fMUNYL6y3cCAL1wgdHKN/SXmmry1zdX0oH6Kwhn7R0PlDLCLJnpsHBQ/pHCAYHJFCPruPAsRltNDmRIF6KDbAN1RGS1WJFN4zvYdbyDRwX8=
